README

diff --git a/rsyncer b/rsyncer
--- a/rsyncer
+++ b/rsyncer
@@ -218,6 +218,15 @@ function verify {
 		echo "ERROR: The rsync binary is not available in this system, please install"
 		exit 1
 	fi
+	.
+	SELECTOR="dialog"
+	whichverify "$SELECTOR"
+	local res=$?
+
+	if [ $res -eq 1 ]; then
+		echo "ERROR: The dialog binary is not available in this system, please install"
+		exit 1
+	fi
 
 	echo "All dependencies is ok!"
 
diff --git a/spanish/rsyncer b/spanish/rsyncer
--- a/spanish/rsyncer
+++ b/spanish/rsyncer
@@ -219,6 +219,15 @@ function verify {
 		exit 1
 	fi
 
+		SELECTOR="dialog"
+	whichverify "$SELECTOR"
+	local res=$?
+
+	if [ $res -eq 1 ]; then
+		echo "ERROR: The ejecutable de dialog, no se encuentra en el sistema, por favor instalalo"
+		exit 1
+	fi
+
 	echo "Todo ok!"
 
 	START=$(date +%s)
